// The Kettlewick showcase (FEAT-039): generated by the real renderers from demo/kettlewick/,
// full by construction, fictional and says so, and gated — a hole on the demo fails the build.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, existsSync, mkdtempSync, rmSync, writeFileSync, cpSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { generate, renderDemo, DEMO, DEMO_PAGES } from '../scripts/gen-demo.js';
import { BOSS_ROOT } from '../src/paths.js';

test('the demo renders with no open question on the playbook, and the VC cut omits the proto-persona', () => {
  const r = generate({ check: true });
  try {
    assert.deepEqual(r.questions, [], `open: ${r.questions.map((q) => q.id).join(', ')}`);
  } finally { rmSync(r.dir, { recursive: true, force: true }); }
  const { dir, data } = renderDemo();
  try {
    assert.ok(data.cuts.vc.includes('persona-marta') && !data.cuts.vc.includes('persona-priya'));
    assert.ok(data.cuts.vc.includes('person-marta') && data.cuts.vc.includes('evidence-ladder'));
    assert.ok(existsSync(join(dir, '.boss', 'design.html')) && existsSync(join(dir, '.boss', 'board.html')));
  } finally { rmSync(dir, { recursive: true, force: true }); }
});

test('the six pages: every one says fictional, links stay relative, nothing is fetched, and no face is drawn', () => {
  const out = mkdtempSync(join(tmpdir(), 'boss-demo-out-'));
  try {
    generate({ out });
    assert.deepEqual(readdirSync(out).sort(), [...DEMO_PAGES].sort());
    for (const p of DEMO_PAGES) {
      const html = readFileSync(join(out, p), 'utf8');
      assert.ok(html.includes('Kettlewick is fictional'), `${p} says fictional`);
      assert.doesNotMatch(html, /<script[^>]+src=|<link\b|@import|url\(/i, `${p} fetches nothing`);
      assert.doesNotMatch(html, /href="https?:\/\/claude\.ai/, `${p} has no artifact link`);
      assert.doesNotMatch(html, /<img\b(?![^>]*src="data:)/i, `${p}: an image only inline`);
    }
    const pb = readFileSync(join(out, 'playbook.html'), 'utf8');
    assert.ok(!pb.includes('class="face"'), 'no faces on the demo');
    assert.ok(pb.includes('<img class="logo" src="data:image/svg+xml'), 'the mark renders from its file');
    assert.ok(pb.includes('href="design.html#persona-marta"'), 'the Design link survives as a sibling');
  } finally { rmSync(out, { recursive: true, force: true }); }
});

test('the folders page is read from the tree; the inside page is the shipped files verbatim', () => {
  const out = mkdtempSync(join(tmpdir(), 'boss-demo-out-'));
  try {
    generate({ out });
    const folders = readFileSync(join(out, 'folders.html'), 'utf8');
    for (const d of ['docs/ideas/', 'docs/evidence/', 'docs/team/', 'docs/competition/']) assert.ok(folders.includes(`${d}</td>`), d);
    assert.ok(folders.includes('<code>/comp-eval</code>'), 'a table README falls back to the verb map');
    const inside = readFileSync(join(out, 'inside.html'), 'utf8');
    const hook = readFileSync(join(BOSS_ROOT, 'stages/L0-quickstart/template/.claude/hooks/conscience.js'), 'utf8').split('\n').slice(0, 40).join('\n');
    const esc = (s) => s.replace(/[&<>"]/g, (m) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[m]));
    assert.ok(inside.includes(esc(hook)), 'the hook is shown as shipped');
    assert.ok(inside.includes('kettlewick') && !inside.includes('{{PROJECT_NAME}}'), 'placeholders filled the way boss new fills them');
  } finally { rmSync(out, { recursive: true, force: true }); }
});

test('check:demo fails on a manufactured hole and passes on the tree as committed', () => {
  const ok = execFileSync('node', [join(BOSS_ROOT, 'scripts', 'check-demo.js')], { encoding: 'utf8' });
  assert.match(ok, /the demo is full/);
  // a copy of the record set with the trust page removed → one hole → exit 1
  const copy = mkdtempSync(join(tmpdir(), 'boss-demo-copy-'));
  try {
    cpSync(DEMO, copy, { recursive: true });
    rmSync(join(copy, 'docs', 'trust'), { recursive: true, force: true });
    const script = readFileSync(join(BOSS_ROOT, 'scripts', 'gen-demo.js'), 'utf8').replace("export const DEMO = join(ROOT, 'demo', 'kettlewick');", `export const DEMO = ${JSON.stringify(copy)};`);
    writeFileSync(join(BOSS_ROOT, 'scripts', '__gen-demo-probe.js'), script);
    const check = readFileSync(join(BOSS_ROOT, 'scripts', 'check-demo.js'), 'utf8').replace("'./gen-demo.js'", "'./__gen-demo-probe.js'");
    writeFileSync(join(BOSS_ROOT, 'scripts', '__check-demo-probe.js'), check);
    let code = 0, err = '';
    try { execFileSync('node', [join(BOSS_ROOT, 'scripts', '__check-demo-probe.js')], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }); } catch (e) { code = e.status; err = String(e.stderr); }
    assert.equal(code, 1);
    assert.match(err, /Trust/);
    assert.match(err, /missing folder: .*docs\/trust/);
  } finally {
    rmSync(copy, { recursive: true, force: true });
    for (const f of ['__gen-demo-probe.js', '__check-demo-probe.js']) rmSync(join(BOSS_ROOT, 'scripts', f), { force: true });
  }
});

test('nothing in the demo names a real person or a real rival — the fiction rules from its README', () => {
  const files = [];
  const walk = (d) => { for (const n of readdirSync(d, { withFileTypes: true })) { const p = join(d, n.name); if (n.isDirectory()) walk(p); else if (/\.(md|csv|json)$/.test(n.name)) files.push(p); } };
  walk(DEMO);
  const text = files.map((f) => readFileSync(f, 'utf8')).join('\n');
  assert.ok(files.length >= 35);
  assert.doesNotMatch(text, /Tidewell/, 'the old name is gone');
  assert.doesNotMatch(text, /photo:\s*\.\//, 'no photo file for a person');
  assert.ok(!existsSync(join(DEMO, 'docs', 'evidence', 'CANDIDATES-2026-08-23-maintainer-experiment.md')), 'nothing copied from BOSS\'s own evidence');
});
