#!/usr/bin/env node
// gen-demo — the Kettlewick showcase (FEAT-039, from IDEA-110).
//
// Renders `demo/kettlewick/` — a fictional venture's record set, tracked — with the SAME
// renderers an install runs (`boss playbook`, `boss design`, `boss board --html`) and writes
// the result into `site/demo/`. Nothing on the demo is drawn by hand: the playbook, the design
// space and the board are the products' own output; the folders page is read from the tree it
// just rendered; the inside page is the shipped files, escaped. A demo prettier than what `boss`
// produces is a lie the first install exposes.
//
//   node scripts/gen-demo.js            # writes site/demo/*.html
//   node scripts/gen-demo.js --check    # renders to a temp dir only; prints the open questions
//
// No `boss new` (nothing lands in ~/.boss/registry.json); the record set is copied to a temp dir,
// stamped, rendered, and the temp dir removed. `gen:site` calls this, so `npm run release`'s
// "site/ up to date" check covers the demo; `check:demo` fails when a hole appears on it.

import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, cpSync, rmSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { playbookHtml, questionsLine } from '../src/playbook.js';
import { designHtml } from '../src/design.js';
import { boardHtml } from '../src/board.js';
import { loadModes } from '../src/modes.js';
import { readEvidence, readPersonas, readDecisions, readBrandDoc, readHealth, readLearnings } from '../src/playbook.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const DEMO = join(ROOT, 'demo', 'kettlewick');
const SITE_DEMO = join(ROOT, 'site', 'demo');
// The pages this script writes — check-site resolves `demo/<page>.html` links against this list.
export const DEMO_PAGES = ['index.html', 'playbook.html', 'design.html', 'board.html', 'organization.html', 'learning.html'];
const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (m) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[m]));

const BANNER = 'Kettlewick is fictional — every page here is generated by <code>boss</code> from the records in <code>demo/kettlewick/</code>, the same way an install renders yours.';
// The site's ribbon. The rendered spaces are the venture's — its name, its tokens, its nav — which
// is the point of the demo and also why a reader who clicked through from the site felt they had
// left it (Ajesh, 2026-09-13). One strip in the SITE's palette above the venture's topbar says
// whose site this is and holds the way back; the fictional note lives in it, so the page carries
// one strip, not two. It wears the site header's own look — concrete ground, hairline, graphite
// text, hi-vis mark (web/styles/tokens.css, light values — paper, persimmon, cornflower; the mark is gen-site's MARK_PATH, copied) — inlined because these pages carry only
// the venture's stylesheet. A graphite bar was tried first and read as a different site.
const SITE_NAV = [['index.html', 'Home'], ['start.html', 'Start'], ['guide.html', 'Guide'], ['demo.html', 'Demo'], ['about.html', 'About']];
const RIBBON_CSS = `
  .site-ribbon { display: flex; flex-wrap: wrap; align-items: center; gap: 6px 18px; padding: 8px 20px; background: #F6F6F3; color: #14202B; font-family: ui-monospace, Menlo, Consolas, monospace; font-size: 12px; line-height: 1.5; border-bottom: 1px solid #CDD5DB; }
  .site-ribbon a { color: #4A5A68; text-decoration: none; }
  .site-ribbon a:hover, .site-ribbon a:focus-visible { color: #14202B; text-decoration: underline; }
  .site-ribbon .wm { color: #14202B; font-weight: 700; letter-spacing: 0.06em; } .site-ribbon .wm .mk { width: 1.05em; height: 1.05em; vertical-align: -0.16em; margin-right: 6px; color: #FF5C34; } .site-ribbon .wm em { font-style: normal; color: #FF5C34; }
  .site-ribbon .full { color: #4A5A68; letter-spacing: 0; margin-left: -8px; }
  .site-ribbon nav { display: flex; flex-wrap: wrap; gap: 0 14px; } .site-ribbon nav a.on { color: #14202B; border-bottom: 2px solid #5089E0; }
  .site-ribbon .note { color: #4A5A68; margin-left: auto; max-width: 60ch; } .site-ribbon .note code { font: inherit; color: #14202B; }
  @media (max-width: 720px) { .site-ribbon .note { margin-left: 0; max-width: none; } .site-ribbon .full { display: none; } }`;
const RIBBON = `<div class="site-ribbon" role="banner">
  <a class="wm" href="../index.html"><svg class="mk" viewBox="0 0 100 100" aria-hidden="true" focusable="false"><path fill="currentColor" d="M50 0 L64 36 L100 50 L64 64 L50 100 L36 64 L0 50 L36 36 Z"/></svg>B<em>.</em>O<em>.</em>S<em>.</em>S<em>.</em></a><span class="full">Build Out Solid Stuff</span>
  <nav aria-label="oyeboss.build">${SITE_NAV.map(([f, l]) => `<a href="../${f}"${f === 'demo.html' ? ' class="on"' : ''}>${l}</a>`).join('')}</nav>
  <span class="note">The demo. ${BANNER}</span>
</div>`;

// Copy the record set to a temp project, stamp it, render the three spaces there (the family bar
// looks for its siblings in the same .boss/), and hand back the paths.
export function renderDemo() {
  const project = JSON.parse(readFileSync(join(DEMO, 'project.json'), 'utf8'));
  const dir = mkdtempSync(join(tmpdir(), 'boss-demo-'));
  cpSync(DEMO, dir, { recursive: true });
  mkdirSync(join(dir, '.boss'), { recursive: true });
  writeFileSync(join(dir, '.boss', 'manifest.json'), JSON.stringify({ name: project.name, stage: project.stage, mode: project.mode, cohort: project.cohort, version: project.bossVersion, created: project.created }, null, 2));
  if (project.cohort) writeFileSync(join(dir, '.boss', 'config.json'), JSON.stringify({ cohort: project.cohort, team: [{ handle: '@ola', name: 'Ola Bennett', added: '2026-06-01' }] }, null, 2));
  // the loops and hooks an install lays down for this stage — copied from the templates, so the
  // conscience can be run for real against the records (never a manufactured log)
  for (const stage of ['L0-quickstart', 'L1-mvp']) {
    const loops = join(ROOT, 'stages', stage, 'template', '.boss', 'loops');
    if (existsSync(loops)) cpSync(loops, join(dir, '.boss', 'loops'), { recursive: true });
    const hooks = join(ROOT, 'stages', stage, 'template', '.claude', 'hooks');
    if (existsSync(hooks)) cpSync(hooks, join(dir, '.claude', 'hooks'), { recursive: true });
  }
  // render order matters only for the family bar: the last one rendered sees the other two on disk,
  // so render twice — cheap, and every page's bar then links to both siblings.
  const once = () => { boardHtml(dir, project.name); designHtml(dir, project.name); return playbookHtml(dir, project.name); };
  once();
  const { data } = once();
  const design = designHtml(dir, project.name).data; boardHtml(dir, project.name);
  return { dir, project, data, design, conscience: runConscience(dir), pages: { playbook: join(dir, '.boss', 'playbook.html'), design: join(dir, '.boss', 'design.html'), board: join(dir, '.boss', 'board.html') } };
}

// The conscience, run for real: the shipped hook (`.claude/hooks/conscience.js`) against the demo
// tree, exactly as the host would run it on a prompt. What comes back is a SCHEMA — loop, moment,
// confidence, the predicate's evidence — and the loop file's own opening sentence; Claude composes
// the voice at the desk, and this page composes nothing. An empty result is silence, shown as such.
export function runConscience(dir) {
  const hook = join(dir, '.claude', 'hooks', 'conscience.js');
  if (!existsSync(hook)) return { ran: false, signals: [] };
  let out = '';
  try { out = execFileSync(process.execPath, [hook], { cwd: dir, input: '{}', encoding: 'utf8', timeout: 20000, stdio: ['pipe', 'pipe', 'ignore'] }); } catch { return { ran: false, signals: [] }; }
  let j = null; try { j = JSON.parse(out).hookSpecificOutput; } catch { return { ran: true, signals: [] }; }
  // the frame the hook hands the model, per signal: its first sentence is the plainest statement
  // of the moment there is (the loop file's prose is BOSS's own history, not the founder's)
  const frames = String(j && j.additionalContext || '').split(/\(\d+\)\s+\[BOSS conscience — /).slice(1);
  const signals = (j && j.signals ? j.signals : []).map((sg, i) => {
    const loopFile = join(dir, '.boss', 'loops', `${sg.loop_id}.md`);
    let opening = '', title = '';
    try { title = (readFileSync(loopFile, 'utf8').replace(/^---\n[\s\S]*?\n---\n?/, '').match(/^#\s+(.+)$/m) || [null, ''])[1].trim(); } catch { /* a loop with no prose is still a signal */ }
    const frame = (frames[i] || '').replace(/^[^\]]*\]\s*/, '');
    const m = frame.match(/^(.{12,}?[.!?])(\s|$)/);
    opening = (m ? m[1] : '').replace(/[*_`]/g, '').trim();
    const facts = [];
    for (const e of (sg.evidence && sg.evidence.entry) || []) if (e.count != null) facts.push(`${e.count} match${e.count === 1 ? '' : 'es'} in ${e.files || e.matchedFiles || 0} file${(e.files || e.matchedFiles) === 1 ? '' : 's'} (needs ${e.min})`);
    for (const x of (sg.evidence && sg.evidence.exit) || []) if (x.ok === false) facts.push(x.path ? `missing: ${x.path}` : x.path_glob ? `nothing matching ${x.path_glob}` : `exit not met`);
    return { loop: sg.loop_id, moment: sg.moment, type: sg.type, confidence: sg.confidence, title, opening, facts };
  });
  return { ran: true, signals, cohort: j && j.cohort };
}

// The organization page — from the tree that was just rendered, grouped by what the founder is
// doing, each folder with the verb that writes it and one line that says what a record there IS.
// Never a typed tree: a folder that isn't on disk isn't on the page. The stronger lines below
// are BOSS's own description of its record classes; the counts and samples are read.
const GROUPS = [
  { key: 'idea', title: 'The idea, and what you decided', lead: 'One living doc per idea, a canvas that pressure-tests it, a build contract when it earns one, and every load-bearing call with the signal that would prove it wrong.',
    folders: ['docs/ideas', 'docs/decisions'] },
  { key: 'people', title: 'The people — real and drawn', lead: 'Who it is for as a persona with a ledger that says how much of it is real, and what real people actually said or did, graded — a compliment never reads as a receipt.',
    folders: ['docs/personas', 'docs/evidence', 'docs/team'] },
  { key: 'field', title: 'The field, and what you dropped in', lead: 'Rivals with a checked date and the honest "why they might win"; your own decks and reports, dated on the way in, so a figure from March is never a fact about today.',
    folders: ['docs/competition', 'docs/source', 'docs/dossier'] },
  { key: 'made', title: 'How it looks and sounds', lead: 'The brand as a living doc that starts nascent; the design system as tokens, a style guide, components with usage pages, patterns and flows — each with the decision that chose it.',
    folders: ['docs/brand', 'docs/design', 'docs/design/components', 'docs/design/icons', 'docs/design/library', 'docs/product'] },
  { key: 'going', title: 'How it is going', lead: 'After the first user: one activation metric, one retention curve, a dated health verdict that defaults to pre-fit, and the trust page a buyer can read. The story so far, one entry a session.',
    folders: ['docs/health', 'docs/measure', 'docs/trust', 'docs'] },
  { key: 'machine', title: 'The machine', lead: 'What BOSS installed for the host and the state it keeps for itself — local, never in the repo, and never the founder\'s to maintain.',
    folders: ['.claude', '.boss'] },
];
const WRITES = {
  'docs': { verbs: ['/log', '/close'], line: 'the devlog (what landed, what surprised you, one entry a session), the brand doc, the resume the next session reads first' },
  'docs/ideas': { verbs: ['/idea', '/canvas', '/spec'], line: 'IDEA-NNN — a living idea doc with a sharpening current shape and an append-only capture log; the canvas as thirteen cells; FEAT-NNN — the build contract with acceptance criteria and the paths that must not break' },
  'docs/decisions': { verbs: ['/decide'], line: 'DEC-NNN — context, decision, why, and a falsifier with a date; superseded, never edited' },
  'docs/personas': { verbs: ['/persona'], line: 'one persona per file: who, context, jobs, pains, values, what you don\'t know yet — and a ledger, synthetic vs real, that moves as evidence lands' },
  'docs/evidence': { verbs: ['/evidence', '/interview'], line: 'EVID-NNN — one signal per file, dated, graded stated-pain → observed-behavior → commitment, tied to the assumption it bears on' },
  'docs/team': { verbs: ['boss team add'], line: 'one person per file — the specific thing seen, built, sold or lived; what they bring and don\'t; a role you need and don\'t have, written plainly' },
  'docs/competition': { verbs: ['/comp-eval'], line: 'the field as one table, one file per rival with where it breaks and how they do it, every row with a checked date' },
  'docs/source': { verbs: ['/import'], line: 'your own material — a deck, a report, a saved page — dated in the name; /import reads it and offers the records it could fill' },
  'docs/dossier': { verbs: ['/consult'], line: 'the mentors\' positions, dated — the capital mentor\'s not-yet with its reason is what the playbook quotes as the ask' },
  'docs/brand': { verbs: ['/landing'], line: 'the mark, when there is a file — the brand doc itself lives beside the devlog' },
  'docs/design': { verbs: ['/design-tokens-init', '/design-review', '/ux-check'], line: 'tokens.json, the style guide, components, patterns, flows, the reviews — the design space is a read of these' },
  'docs/design/components': { verbs: ['/design-review'], line: 'one usage page per component, written at its review — when to use it, when not' },
  'docs/design/icons': { verbs: ['/design-review'], line: 'the icon set as SVG files; the design page draws them from here and copies them as a sprite' },
  'docs/design/library': { verbs: ['/design-tokens-init'], line: 'the component manifest — what exists, so the second button is never invented' },
  'docs/product': { verbs: ['/spec'], line: 'JOURNEY.md — the flows as a founder would walk them, written at the first flow' },
  'docs/health': { verbs: ['/health'], line: 'HEALTH-<date> — a verdict, dated: pre-fit by default, the curve when there is one, the one next move' },
  'docs/measure': { verbs: ['/measure'], line: 'MEASURE-<date> — the one activation metric, the one retention curve, at most ten events, the humane note' },
  'docs/trust': { verbs: ['/trust'], line: 'TRUST.md — what you collect, who processes it, how someone reaches you about their data; one honest paragraph' },
  '.boss': { verbs: ['boss'], line: 'the stamp, the config, the conscience\'s read on the venture, the rendered pages — machine state, gitignored' },
  '.claude': { verbs: ['boss new', 'boss unlock'], line: 'agents, skills, hooks and rules for the host — laid down by mode, only what the venture has earned' },
};
function readmeLine(md) {
  const body = String(md).replace(/^---\n[\s\S]*?\n---\n?/, '').split('\n').filter((l) => l.trim() && !/^#/.test(l) && !/^\|/.test(l)).join(' ');
  const m = body.match(/^(.{12,}?[.!?])(\s|$)/);
  return (m ? m[1] : '').replace(/[*_`]/g, '').trim();
}
function scanTree(dir) {
  const rows = new Map();
  const walk = (d) => {
    for (const n of readdirSync(d).sort()) {
      const p = join(d, n); let st; try { st = statSync(p); } catch { continue; }
      if (!st.isDirectory()) continue;
      const rel = relative(dir, p);
      const files = readdirSync(p).filter((f) => { try { return statSync(join(p, f)).isFile(); } catch { return false; } });
      rows.set(rel, { rel, count: files.length, sample: files.filter((f) => !/^readme/i.test(f)).slice(0, 5) });
      walk(p);
    }
  };
  walk(dir);
  return rows;
}
const verbChips = (verbs) => verbs.map((v) => `<span class="verb-chip">${esc(v)}</span>`).join('');
export function organizationHtml(dir, project) {
  const tree = scanTree(dir);
  const records = [...tree.values()].filter((r) => r.rel.startsWith('docs')).reduce((n, r) => n + r.count, 0);
  const verbs = new Set(Object.values(WRITES).flatMap((w) => w.verbs));
  const modes = loadModes().filter((m) => m.authored);
  // what each mode lays down (its template's docs/ dirs) and what its verbs go on to write
  const stageDocs = modes.map((m) => {
    const d = join(ROOT, 'stages', m.id, 'template', 'docs');
    const dirs = existsSync(d) ? readdirSync(d).filter((x) => { try { return statSync(join(d, x)).isDirectory(); } catch { return false; } }).map((x) => `docs/${x}/`) : [];
    const names = new Set((m.skills || []).map((sk) => '/' + (sk.name || sk)));
    const written = Object.entries(WRITES).filter(([f, w]) => w.verbs.some((v) => names.has(v))).map(([f]) => `${f}/`).filter((f) => !dirs.includes(f));
    return { name: m.name, dirs, written, skills: (m.skills || []).length };
  });
  const groups = GROUPS.map((g) => {
    const cards = g.folders.filter((f) => tree.has(f)).map((f) => {
      const r = tree.get(f); const w = WRITES[f] || { verbs: [], line: '' };
      return `<article class="block filled org" id="org-${esc(f.replace(/\W+/g, '-'))}" data-title="${esc(f)}/"><div class="head"><h3><code>${esc(f)}/</code></h3></div><div class="body"><div class="verbs">${verbChips(w.verbs)}</div><p>${esc(w.line)}</p></div><div class="foot"><span class="src">${r.count} file${r.count === 1 ? '' : 's'}${r.sample.length ? ' · ' + esc(r.sample.join(' · ')) : ''}</span></div><div class="actions"></div></article>`;
    });
    return cards.length ? `<section class="chapter" id="org-${g.key}"><div class="chapter-head"><div class="label">${esc(g.title)}</div><p>${esc(g.lead)}</p></div><div class="blocks">${cards.join('')}</div></section>` : '';
  }).join('\n');
  const modeStrip = stageDocs.map((m) => `<div class="mode"><div class="label">${esc(m.name)}</div><p><b class="tab">${m.skills}</b> verbs${m.dirs.length ? ` · lays down <code>${m.dirs.join('</code> <code>')}</code>` : ''}${m.written.length ? ` · its verbs write <code>${m.written.join('</code> <code>')}</code>` : (m.dirs.length ? '' : ' · adds no folder of its own')}</p></div>`).join('');
  return page(project, 'Organization', `
<div class="chapter-head"><div class="label">Organization</div><h2>Every record has a home, a shape, and one verb that writes it.</h2>
<p>This is the part of BOSS that does the filing so the founder never has to. Nothing lives in the chat: what you say becomes a record in a folder, in a fixed shape, with an id and a status line — and the playbook, the design space and the board are <em>reads</em> of those folders, never documents anyone maintains. Change the work and the pages change; there is nothing else to update.</p></div>
<div class="facts"><div class="fact"><b class="tab">${records}</b><span>records on disk</span></div><div class="fact"><b class="tab">${[...tree.keys()].filter((k) => k.startsWith('docs')).length}</b><span>folders under <code>docs/</code></span></div><div class="fact"><b class="tab">${verbs.size}</b><span>verbs that write them</span></div><div class="fact"><b class="tab">4</b><span>id classes — IDEA · FEAT · DEC · EVID</span></div></div>
<section class="chapter" id="org-rules"><div class="chapter-head"><div class="label">The four rules it keeps</div></div>
<div class="blocks">
  <article class="block filled" id="org-rule-1" data-title="One verb, one shape"><div class="head"><h3>One verb, one shape</h3></div><div class="body"><p>A persona is always six fields and a ledger; a decision always carries a falsifier with a date; evidence is always one signal, graded. The shape is what lets a page be a read instead of a rewrite.</p></div><div class="foot"><span class="src">the shipped skills' templates</span></div><div class="actions"></div></article>
  <article class="block filled" id="org-rule-2" data-title="Status is truth"><div class="head"><h3>The status line is the truth</h3></div><div class="body"><p><code>captured · ready · building · shipped · deferred · dropped</code> — a word on the record's own frontmatter. The board reads it; nobody drags a card. A parked idea carries its re-open trigger in the same line.</p></div><div class="foot"><span class="src">docs/IDS.md · boss board</span></div><div class="actions"></div></article>
  <article class="block filled" id="org-rule-3" data-title="Folders arrive by mode"><div class="head"><h3>Folders arrive as the venture earns them</h3></div><div class="body"><div class="modes">${modeStrip}</div></div><div class="foot"><span class="src">stages/*/template · read at build time</span></div><div class="actions"></div></article>
  <article class="block filled" id="org-rule-4" data-title="Nothing invented"><div class="head"><h3>Nothing is written without a yes, nothing is filled from imagination</h3></div><div class="body"><p>Drop a deck in <code>docs/source/</code> and BOSS says which records it could fill and writes each only when you say so. A field nobody answered stays a hole on the page — a confident answer arrived at with no information is worse than a blank.</p></div><div class="foot"><span class="src">/import · the playbook's holes</span></div><div class="actions"></div></article>
</div></section>
${groups}`);
}

// The learning page — how the venture learned, read from its own records: the ladder climbing,
// a persona's ledger moving, a decision proven wrong, the brand learning real words, a health
// read turning into the next idea, and the modes that gave the founder each verb when earned.
export function learningHtml(dir, project, conscience = { ran: false, signals: [] }) {
  const ev = readEvidence(dir).sort((a, b) => String(a.date).localeCompare(String(b.date)));
  const GR = ['stated-pain', 'observed-behavior', 'commitment'];
  const ladder = ev.map((e) => `<li><span class="date">${esc(e.date || 'undated')}</span> <span class="chip ${e.grade === 'stated-pain' ? 'asserted' : 'ev'}">${esc(e.grade)}</span> ${esc(e.title)}</li>`).join('');
  const climbed = ev.length ? `${GR.filter((g) => ev.some((e) => e.grade === g)).length} of 3 rungs reached` : 'no signal yet';
  const personas = readPersonas(dir);
  const p = personas.find((x) => x.real > 0);
  const pText = p ? readFileSync(join(dir, 'docs', 'personas', `${p.slug}.md`), 'utf8') : '';
  const refactors = [...pText.matchAll(/^\s*[-*]\s+(\d{4}-\d{2}-\d{2})\s*[—–-]+\s*(.+)$/gm)].map((m) => `<li><span class="date">${esc(m[1])}</span> ${esc(m[2])}</li>`).join('');
  const decs = readDecisions(dir, Date.now());
  const wrong = decs.find((d) => d.supersededBy && d.outcome);
  const brand = readBrandDoc(dir);
  const brandText = brand ? readFileSync(join(dir, 'docs', 'BRAND.md'), 'utf8') : '';
  const learnedRows = [...brandText.matchAll(/^\|\s*(\d{4}-\d{2}-\d{2})\s*\|[^|]*\|\s*([^|]+?)\s*\|/gm)].map((m) => `<li><span class="date">${esc(m[1])}</span> ${esc(m[2].replace(/[*_`]/g, ''))}</li>`).join('');
  const health = readHealth(dir);
  const learn = readLearnings(dir, 20);
  const fromHealth = learn.entries.filter((e) => /health|filled once|second Monday/i.test(e.landed + ' ' + e.surprises)).slice(0, 2);
  const modes = loadModes().filter((m) => m.authored).slice(0, 2);
  const modeCards = modes.map((m) => `<article class="block filled" id="learn-mode-${esc(m.id)}" data-title="${esc(m.name)}"><div class="head"><h3>${esc(m.name)}</h3></div><div class="body"><p class="t-small">${esc(m.summary || '')}</p><div class="verbs">${(m.skills || []).map((sk) => `<span class="verb-chip">/${esc(sk.name || sk)}</span>`).join('')}</div></div><div class="foot"><span class="src">stages/${esc(m.id)}/manifest.json</span></div><div class="actions"></div></article>`).join('');
  const block = (id, title, sub, body, src) => `<article class="block filled" id="${id}" data-title="${esc(title)}"><div class="head"><h3>${esc(title)}${sub ? ` <span class="sub">— ${esc(sub)}</span>` : ''}</h3></div><div class="body">${body}</div><div class="foot"><span class="src">${esc(src)}</span></div><div class="actions"></div></article>`;
  return page(project, 'Learning', `
<div class="chapter-head"><div class="label">How it learns</div><h2>What ${esc(project.name)} found out, in the order it found it out — read from the records.</h2>
<p>BOSS doesn't grade a venture; it keeps the trail honest. Each block below is a record class doing the thing it exists for: evidence climbing a ladder, a persona getting less made-up, a decision failing its own test, a brand learning the words real people use, and a health read turning into the next idea.</p></div>
<div class="blocks">
${block('learn-ladder', 'Evidence climbed the ladder', climbed, `<ol class="trail">${ladder}</ol><p class="t-small">stated-pain is what someone said; observed-behavior is what you watched them do; commitment is what they gave up — money, time, a name.</p>`, 'docs/evidence · four records, graded')}
${p ? block('learn-persona', `${p.name} got less made-up`, `synthetic ${p.synthetic}% · real ${p.real}%`, `<p>The persona started 100% synthetic — a guess with a name. Each real conversation shifted the ledger and left a dated line:</p><ol class="trail">${refactors}</ol>`, `docs/personas/${p.slug}.md · Notable refactors`) : ''}
${wrong ? block('learn-decision', 'A decision failed its own test', wrong.id, `<p><strong>${esc(wrong.title)}</strong> — ${esc(wrong.decision)}</p><p class="fals"><strong>Falsifier —</strong> ${esc(wrong.falsifier)}</p><p><strong>Outcome:</strong> ${esc(wrong.outcome)}</p>`, `docs/decisions/${wrong.file} · superseded by ${wrong.supersededBy}`) : ''}
${brand ? block('learn-brand', 'The brand learned real words', `${brand.learned.count} rows, from evidence`, `<p>The brand doc starts nascent and only grows from things that actually happened — never from brainstorming. What each one said about the brand:</p><ol class="trail">${learnedRows}</ol>`, 'docs/BRAND.md · What we\'ve learned') : ''}
${health && health.health ? block('learn-health', 'A health read became the next idea', health.health.date, `<p>${esc(health.health.text)}</p>${fromHealth.length ? `<ol class="trail">${fromHealth.map((e) => `<li><span class="date">${esc(e.date)}</span> ${esc(e.landed)}${e.surprises ? ` — ${esc(e.surprises)}` : ''}</li>`).join('')}</ol>` : ''}<p class="t-small">Pre-fit by default. At n under ten, the verdict is <em>talk to them</em>, never a score.</p>`, `${health.health.file} · docs/devlog.md`) : ''}
</div>
<section class="chapter" id="learn-conscience"><div class="chapter-head"><div class="label">The conscience, run against these records</div><p>${conscience.ran ? `The shipped hook was run on this exact tree while this page was built — the same <code>.claude/hooks/conscience.js</code> an install fires on every prompt. It returns a <em>signal</em>, not a sentence: which loop, which moment, how confident, and the file facts behind it. At the founder's desk the model turns that into one spare line, once; here you see the schema.${conscience.cohort ? ` Cohort read from the project: <code>${esc(conscience.cohort)}</code>.` : ''}` : 'The hook could not be run at build time; nothing is shown in its place.'}</p></div>
<div class="blocks">${conscience.signals.length ? conscience.signals.map((sg, i) => `<article class="block filled signal" id="signal-${esc(sg.loop)}" data-title="${esc(sg.loop)}"><div class="head"><h3>${esc(sg.title || sg.loop)} <span class="sub">— ${esc(sg.moment)} · ${esc(sg.confidence)} confidence</span></h3></div><div class="body">${sg.opening ? `<p>${esc(sg.opening)}</p>` : ''}<ul class="facts-list">${sg.facts.map((f) => `<li><code>${esc(f)}</code></li>`).join('')}</ul></div><div class="foot"><span class="chip ${sg.moment === 'done' ? 'ev' : 'find'}">${esc(sg.type)}</span><span class="src">.boss/loops/${esc(sg.loop)}.md · run ${new Date().toISOString().slice(0, 10)}</span></div><div class="actions"></div></article>`).join('') : (conscience.ran ? `<article class="block dormant" id="signal-none" data-title="silence"><div class="head"><h3>Nothing to say</h3></div><div class="body"><p class="prompt">Every loop's exit is met. The conscience stays quiet the rest of the time — that is the design, not a gap.</p></div><div class="foot"><span class="src">.boss/loops · run ${new Date().toISOString().slice(0, 10)}</span></div><div class="actions"></div></article>` : '')}</div></section>
<section class="chapter" id="learn-modes"><div class="chapter-head"><div class="label">And the verbs arrived as they were earned</div><p>Quickstart gives a founder the capture-and-talk-to-one-person loop and nothing else; MVP adds the build, the ship and the measure. A mode is unlocked by the founder, when the canvas holds — not by a calendar.</p></div><div class="blocks two">${modeCards}</div></section>`);
}

// A page in the family's chrome, without importing the shell's private pieces: one topbar, one
// column, the same tokens the rendered pages carry (copied from the rendered playbook's <style>).
let SHELL_CSS = null;
function page(project, title, inner) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(project.name)} — ${esc(title)}</title>
<style>${SHELL_CSS || ''}
  .verbs { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 10px; } .verb-chip { display: inline-flex; padding: 2px 9px; border-radius: 99px; background: var(--accent); color: var(--accent-ink); font-family: var(--mono); font-size: 11px; letter-spacing: .02em; }
  .facts { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 12px; margin: 0 0 28px; } .fact { background: var(--paper); border: 1px solid var(--rule); border-radius: 8px; padding: 14px 16px; } .fact b { display: block; font-family: var(--display); font-size: 34px; line-height: 1; margin-bottom: 6px; } .fact span { font-size: 13px; color: var(--ink-2); }
  .modes { display: grid; gap: 10px; } .mode p { margin-top: 2px; font-size: 14px; }
  .facts-list { margin: 8px 0 0; padding-left: 18px; font-size: 13px; } .facts-list li + li { margin-top: 4px; } .block.signal .body p { font-size: 14.5px; }
  .trail { margin: 8px 0 0; padding-left: 18px; } .trail li + li { margin-top: 6px; } .trail .date { font-family: var(--mono); font-size: 11px; color: var(--muted); margin-right: 6px; } .block .fals { margin-top: 8px; color: var(--ink-2); font-size: 14px; }
  main.one .chapter { padding-block: 20px 36px; }
${RIBBON_CSS}
  main.one { max-width: 1100px; margin: 0 auto; padding: 32px 20px 80px; } .src-file { font-family: var(--mono); font-size: 12px; line-height: 1.5; white-space: pre-wrap; overflow-wrap: anywhere; background: var(--ground); border-radius: 6px; padding: 12px 14px; margin: 10px 0 0; max-height: 640px; overflow: auto; }
</style>
</head>
<body>
${RIBBON}
<header class="topbar">
  <div class="wordmark">${esc(project.name)}</div>
  <nav class="family" aria-label="Spaces"><a href="index.html">Demo</a><a href="playbook.html">Playbook</a><a href="design.html">Design</a><a href="board.html">Board</a><a href="organization.html"${title === 'Organization' ? ' class="on" aria-current="page"' : ''}>Organization</a><a href="learning.html"${title === 'Learning' ? ' class="on" aria-current="page"' : ''}>Learning</a></nav>
</header>
<main class="one">
${inner}
</main>
</body>
</html>
`;
}

// Stamp the rendered spaces with the site's ribbon (above the venture's topbar) and a Demo link in
// the family nav.
function stamp(html) {
  const out = html
    .replace('</head>', `<style>${RIBBON_CSS}</style>\n</head>`)
    .replace(/<body[^>]*>/, (m) => `${m}\n${RIBBON}`);
  return out.replace('<nav class="family" aria-label="Spaces">', '<nav class="family" aria-label="Spaces"><a href="index.html">Demo</a>');
}

export function generate({ out = SITE_DEMO, check = false } = {}) {
  const { dir, project, data, design, pages, conscience } = renderDemo();
  try {
    const playbook = readFileSync(pages.playbook, 'utf8');
    SHELL_CSS = (playbook.match(/<style>([\s\S]*?)<\/style>/) || [null, ''])[1];
    const questions = data.questions || [];
    // The design page's own open list (boss design --questions): the same shape, gated the same way.
    const designQuestions = (design && design.questions) || [];
    if (check) return { questions, designQuestions, line: `${questionsLine(questions)} · design: ${questionsLine(designQuestions)}`, dir };
    mkdirSync(out, { recursive: true });
    writeFileSync(join(out, 'playbook.html'), stamp(playbook));
    writeFileSync(join(out, 'design.html'), stamp(readFileSync(pages.design, 'utf8')));
    writeFileSync(join(out, 'board.html'), stamp(readFileSync(pages.board, 'utf8')));
    writeFileSync(join(out, 'organization.html'), organizationHtml(dir, project));
    writeFileSync(join(out, 'learning.html'), learningHtml(dir, project, conscience));
    writeFileSync(join(out, 'index.html'), page(project, 'Demo', `
<div class="chapter-head"><div class="label">The demo</div><h2>One venture, every piece, generated.</h2><p>Kettlewick is a fictional venture that finds shift cover for small home-care agencies — a phone-first way to find cover when a carer calls in sick. Nothing here is a mock-up: the pages below are what <code>boss playbook</code>, <code>boss design</code> and <code>boss board --html</code> produce from the records in <code>demo/kettlewick/</code>, which you can read in the repo.</p></div>
<div class="blocks">
  <article class="block filled" id="demo-playbook" data-title="Playbook"><div class="head"><h3><a href="playbook.html">The playbook →</a></h3></div><div class="body"><p>Sixteen chapters over the records: the pitch, the proof, the company. The canvas in three frames. Present it as a deck — the VC cut, or everything — and export the cut as a PDF.</p></div><div class="foot"><span class="src">boss playbook · ${questions.length} question${questions.length === 1 ? '' : 's'} open</span></div></article>
  <article class="block filled" id="demo-design" data-title="Design"><div class="head"><h3><a href="design.html">The design space →</a></h3></div><div class="body"><p>Tokens as swatches with the decision that chose them, contrast computed, the people, the parts, the patterns — every value copies in the form an editor wants.</p></div><div class="foot"><span class="src">boss design</span></div></article>
  <article class="block filled" id="demo-board" data-title="Board"><div class="head"><h3><a href="board.html">The board →</a></h3></div><div class="body"><p>Every idea and feature by where it stands — captured, taking shape, building, shipped, parked — read from the records' own status lines.</p></div><div class="foot"><span class="src">boss board --html</span></div></article>
  <article class="block filled" id="demo-organization" data-title="Organization"><div class="head"><h3><a href="organization.html">Organization →</a></h3></div><div class="body"><p>Every record has a home, a shape and one verb that writes it — the filing BOSS does so the founder never has to, grouped by what you're doing, read from the tree after rendering.</p></div><div class="foot"><span class="src">the demo project's tree</span></div></article>
  <article class="block filled" id="demo-learning" data-title="Learning"><div class="head"><h3><a href="learning.html">How it learns →</a></h3></div><div class="body"><p>Evidence climbing the ladder, a persona getting less made-up, a decision failing its own test, a brand learning real words, a health read becoming the next idea — and the conscience run for real against the records while the page was built.</p></div><div class="foot"><span class="src">read from the records · the shipped hook, run at build time</span></div></article>
</div>
<p class="t-small" style="margin-top:24px">No faces: the founders are fictional, and BOSS never draws a stand-in for a person with no photo. No real company is a rival here. What you see is the render's honesty, not a brochure — the questions still open on the playbook are open on purpose only when a page says so.</p>`));
    return { out, questions, line: questionsLine(questions) };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  const r = generate({ check });
  if (check) { console.log(r.line); for (const q of r.questions) console.log(`  · ${q.title} — ${q.line}`); rmSync(r.dir, { recursive: true, force: true }); }
  else console.log(`  ✦ demo → ${relative(ROOT, r.out)}/ · ${r.line}`);
}
