#!/usr/bin/env node
// gen-demo — the Kettlewick showcase (FEAT-039, from IDEA-110).
//
// Renders `demo/kettlewick/` — a fictional venture's record set, tracked — with the SAME
// renderers an install runs (`boss playbook`, `boss design`, `boss board --html`) and writes
// the result into `site/demo/`. Nothing on the demo is drawn by hand: the playbook, the design
// space and the board are the products' own output; the folders page is read from the tree it
// just rendered; the inside page is the shipped files, escaped. A demo prettier than what `boss`
// produces is a lie the first install exposes.
//
//   node scripts/gen-demo.js            # writes site/demo/*.html
//   node scripts/gen-demo.js --check    # renders to a temp dir only; prints the open questions
//
// No `boss new` (nothing lands in ~/.boss/registry.json); the record set is copied to a temp dir,
// stamped, rendered, and the temp dir removed. `gen:site` calls this, so `npm run release`'s
// "site/ up to date" check covers the demo; `check:demo` fails when a hole appears on it.

import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, cpSync, rmSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { playbookHtml, questionsLine } from '../src/playbook.js';
import { designHtml } from '../src/design.js';
import { boardHtml } from '../src/board.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const DEMO = join(ROOT, 'demo', 'kettlewick');
const SITE_DEMO = join(ROOT, 'site', 'demo');
// The pages this script writes — check-site resolves `demo/<page>.html` links against this list.
export const DEMO_PAGES = ['index.html', 'playbook.html', 'design.html', 'board.html', 'folders.html', 'inside.html'];
const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (m) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[m]));

const BANNER = 'Kettlewick is fictional — every page here is generated by <code>boss</code> from the records in <code>demo/kettlewick/</code>, the same way an install renders yours.';

// Copy the record set to a temp project, stamp it, render the three spaces there (the family bar
// looks for its siblings in the same .boss/), and hand back the paths.
export function renderDemo() {
  const project = JSON.parse(readFileSync(join(DEMO, 'project.json'), 'utf8'));
  const dir = mkdtempSync(join(tmpdir(), 'boss-demo-'));
  cpSync(DEMO, dir, { recursive: true });
  mkdirSync(join(dir, '.boss'), { recursive: true });
  writeFileSync(join(dir, '.boss', 'manifest.json'), JSON.stringify({ name: project.name, stage: project.stage, mode: project.mode, cohort: project.cohort, version: project.bossVersion, created: project.created }, null, 2));
  if (project.cohort) writeFileSync(join(dir, '.boss', 'config.json'), JSON.stringify({ cohort: project.cohort, team: [{ handle: '@ola', name: 'Ola Bennett', added: '2026-06-01' }] }, null, 2));
  // render order matters only for the family bar: the last one rendered sees the other two on disk,
  // so render twice — cheap, and every page's bar then links to both siblings.
  const once = () => { boardHtml(dir, project.name); designHtml(dir, project.name); return playbookHtml(dir, project.name); };
  once();
  const { data } = once();
  designHtml(dir, project.name); boardHtml(dir, project.name);
  return { dir, project, data, pages: { playbook: join(dir, '.boss', 'playbook.html'), design: join(dir, '.boss', 'design.html'), board: join(dir, '.boss', 'board.html') } };
}

// The folders page — from the tree that was just rendered. Each directory: the first sentence of
// its README when it has one, else the verb that writes it (a small map), else nothing said.
const WRITES = {
  'docs': 'everything the venture knows, as records — commits with the repo',
  'docs/ideas': '`/idea` (IDEA-NNN, the living idea doc), `/canvas` (the pressure test), `/spec` (FEAT-NNN, the build contract)',
  'docs/personas': '`/persona derive | enrich | consult` — six fields and an evidence ledger',
  'docs/evidence': '`/evidence`, `/interview` — what real people said or did, graded on the ladder',
  'docs/decisions': '`/decide` — DEC-NNN: context, decision, why, a falsifier with a date',
  'docs/competition': '`/comp-eval` — the field as a table, one file per rival, checked dates',
  'docs/source': '`/import` — the founder\'s own material, dated; the playbook lists it',
  'docs/team': '`boss team add`, or by hand — one person per file',
  'docs/dossier': 'the mentors\' positions, dated — `/consult`',
  'docs/health': '`/health` — the post-launch verdict, dated',
  'docs/measure': '`/measure` — one activation metric, one retention curve, ≤10 events',
  'docs/trust': '`/trust` — the honest paragraph a user or a buyer can read',
  'docs/brand': 'the mark, when there is a file — never a placeholder',
  'docs/design': '`/design-tokens-init`, `/design-review`, `/ux-check` — tokens, style guide, components, patterns, flows',
  'docs/design/components': 'one usage page per component, written at its review',
  'docs/design/icons': 'the icon set as files — `boss design` draws them from here',
  'docs/design/library': 'the component manifest',
  'docs/product': '`/spec` writes JOURNEY.md at the first flow',
  '.boss': 'the machine state — the stamp, the conscience\'s read, the rendered pages; local, gitignored',
  '.claude': 'what BOSS installed for the host: agents, skills, hooks, rules',
};
function firstSentence(md) {
  const body = String(md).replace(/^---\n[\s\S]*?\n---\n?/, '').split('\n').filter((l) => l.trim() && !/^#/.test(l)).join(' ');
  const m = body.match(/^(.{12,}?[.!?])(\s|$)/);
  return (m ? m[1] : body.slice(0, 160)).replace(/[*_`]/g, '').trim();
}
export function foldersHtml(dir, project) {
  const rows = [];
  const walk = (d, depth) => {
    for (const n of readdirSync(d).sort()) {
      const p = join(d, n); let st; try { st = statSync(p); } catch { continue; }
      if (!st.isDirectory()) continue;
      const rel = relative(dir, p);
      const readme = ['README.md', 'readme.md'].map((r) => join(p, r)).find(existsSync);
      const files = readdirSync(p).filter((f) => { try { return statSync(join(p, f)).isFile(); } catch { return false; } });
      // a README that IS the record (the competition table) has no first sentence to speak of
      const fromReadme = readme ? firstSentence(readFileSync(readme, 'utf8')) : '';
      const line = fromReadme && !/^\|/.test(fromReadme) ? fromReadme : (WRITES[rel] || '');
      rows.push({ rel, depth, line, count: files.length, sample: files.filter((f) => !/^readme/i.test(f)).slice(0, 4) });
      walk(p, depth + 1);
    }
  };
  walk(dir, 0);
  const body = rows.map((r) => `<tr><td class="mono" style="padding-left:${10 + r.depth * 18}px">${esc(r.rel)}/</td><td>${r.line ? esc(r.line).replace(/`([^`]+)`/g, '<code>$1</code>') : '<em class="hole-text">—</em>'}</td><td class="mono t-small">${r.count} file${r.count === 1 ? '' : 's'}${r.sample.length ? ' · ' + esc(r.sample.join(', ')) : ''}</td></tr>`).join('\n');
  return page(project, 'Folders', `
<div class="chapter-head"><div class="label">The folders</div><h2>How ${esc(project.name)} is organised on disk.</h2><p>Read from the demo project's own tree after it was rendered — never typed. Every folder's line is its README's first sentence or the verb that writes there.</p></div>
<div class="tscroll"><table class="t"><thead><tr><th>Folder</th><th>What lives here, and which verb writes it</th><th>Files</th></tr></thead><tbody>
${body}
</tbody></table></div>`);
}

// The inside page — the shipped files, as they ship, escaped. Read from stages/ at build time so
// the demo can never show a CLAUDE.md the template doesn't have.
const INSIDE = [
  { file: 'stages/L0-quickstart/template/CLAUDE.md', why: 'read on every turn — the host-specific layer, kept to a screen' },
  { file: 'stages/L0-quickstart/template/AGENTS.md', why: 'the host-neutral working rules; CLAUDE.md imports it' },
  { file: 'stages/L0-quickstart/template/.claude/agents/mentor-founder.md', why: 'one of the mentors — advisory only, never writes product code', head: 60 },
  { file: 'stages/L0-quickstart/template/.claude/skills/canvas/SKILL.md', why: 'one of the skills — a verb the founder runs; this is the pressure test', head: 60 },
  { file: 'stages/L0-quickstart/template/.claude/hooks/conscience.js', why: 'the conscience hook — reads the loops, returns signals; Claude composes the voice', head: 40 },
];
export function insideHtml(project) {
  const blocks = INSIDE.map((f) => {
    const text = readFileSync(join(ROOT, f.file), 'utf8').replace(/\{\{PROJECT_NAME\}\}/g, project.name).replace(/\{\{MODE\}\}/g, 'MVP').replace(/\{\{STAGE\}\}/g, 'L1-mvp').replace(/\{\{DATE\}\}/g, project.created).replace(/\{\{BOSS_VERSION\}\}/g, project.bossVersion);
    const lines = text.split('\n');
    const shown = f.head ? lines.slice(0, f.head) : lines;
    const more = f.head && lines.length > f.head ? `<p class="t-small">… ${lines.length - f.head} more lines in the shipped file.</p>` : '';
    return `<article class="block filled" id="inside-${esc(f.file.split('/').pop().replace(/\W+/g, '-').toLowerCase())}" data-title="${esc(f.file.split('/').pop())}"><div class="head"><h3>${esc(f.file.replace(/^stages\/L0-quickstart\/template\//, ''))}</h3></div><div class="body"><p class="t-small">${esc(f.why)}</p><pre class="src-file">${esc(shown.join('\n'))}</pre>${more}</div><div class="foot"><span class="src">${esc(f.file)} · as shipped in this version</span></div><div class="actions"></div></article>`;
  }).join('\n');
  return page(project, 'Inside the folder', `
<div class="chapter-head"><div class="label">Inside the folder</div><h2>What BOSS put in the project, as it ships.</h2><p>Five of the files an install lays down, read from the template at build time and shown unedited. The placeholders are filled the way <code>boss new</code> fills them.</p></div>
<div class="blocks one">${blocks}</div>`);
}

// A page in the family's chrome, without importing the shell's private pieces: one topbar, one
// column, the same tokens the rendered pages carry (copied from the rendered playbook's <style>).
let SHELL_CSS = null;
function page(project, title, inner) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(project.name)} — ${esc(title)}</title>
<style>${SHELL_CSS || ''}
  .demo-banner { font-family: var(--mono); font-size: 11.5px; color: var(--ink-2); padding: 8px 20px; background: var(--paper); border-bottom: 1px solid var(--rule); }
  main.one { max-width: 1100px; margin: 0 auto; padding: 32px 20px 80px; } .src-file { font-family: var(--mono); font-size: 12px; line-height: 1.5; white-space: pre-wrap; overflow-wrap: anywhere; background: var(--ground); border-radius: 6px; padding: 12px 14px; margin: 10px 0 0; max-height: 640px; overflow: auto; }
</style>
</head>
<body>
<header class="topbar">
  <div class="wordmark">${esc(project.name)}</div>
  <nav class="family" aria-label="Spaces"><a href="index.html">Demo</a><a href="playbook.html">Playbook</a><a href="design.html">Design</a><a href="board.html">Board</a><a href="folders.html"${title === 'Folders' ? ' class="on" aria-current="page"' : ''}>Folders</a><a href="inside.html"${title === 'Inside the folder' ? ' class="on" aria-current="page"' : ''}>Inside</a></nav>
</header>
<div class="demo-banner">${BANNER}</div>
<main class="one">
${inner}
</main>
</body>
</html>
`;
}

// Stamp the rendered spaces with the fictional banner and a link back to the demo's front page.
function stamp(html) {
  const banner = `<div class="demo-banner" style="font-family:ui-monospace,Menlo,monospace;font-size:11.5px;padding:8px 20px;border-bottom:1px solid #C4C8CC;background:#F0F2F3;color:#565C62">${BANNER} <a href="index.html">← the demo</a></div>`;
  const out = html.includes('<div class="shell">')
    ? html.replace('<div class="shell">', `${banner}\n<div class="shell">`)
    : html.replace(/<body[^>]*>/, (m) => `${m}\n${banner}`);
  return out.replace('<nav class="family" aria-label="Spaces">', '<nav class="family" aria-label="Spaces"><a href="index.html">Demo</a>');
}

export function generate({ out = SITE_DEMO, check = false } = {}) {
  const { dir, project, data, pages } = renderDemo();
  try {
    const playbook = readFileSync(pages.playbook, 'utf8');
    SHELL_CSS = (playbook.match(/<style>([\s\S]*?)<\/style>/) || [null, ''])[1];
    const questions = data.questions || [];
    if (check) return { questions, line: questionsLine(questions), dir };
    mkdirSync(out, { recursive: true });
    writeFileSync(join(out, 'playbook.html'), stamp(playbook));
    writeFileSync(join(out, 'design.html'), stamp(readFileSync(pages.design, 'utf8')));
    writeFileSync(join(out, 'board.html'), stamp(readFileSync(pages.board, 'utf8')));
    writeFileSync(join(out, 'folders.html'), foldersHtml(dir, project));
    writeFileSync(join(out, 'inside.html'), insideHtml(project));
    writeFileSync(join(out, 'index.html'), page(project, 'Demo', `
<div class="chapter-head"><div class="label">The demo</div><h2>One venture, every piece, generated.</h2><p>Kettlewick is a fictional home-care rota venture — a phone-first way to find cover when a carer calls in sick. Nothing here is a mock-up: the pages below are what <code>boss playbook</code>, <code>boss design</code> and <code>boss board --html</code> produce from the records in <code>demo/kettlewick/</code>, which you can read in the repo.</p></div>
<div class="blocks">
  <article class="block filled" id="demo-playbook" data-title="Playbook"><div class="head"><h3><a href="playbook.html">The playbook →</a></h3></div><div class="body"><p>Sixteen chapters over the records: the pitch, the proof, the company. The canvas in three frames. Present it as a deck — the VC cut, or everything — and export the cut as a PDF.</p></div><div class="foot"><span class="src">boss playbook · ${questions.length} question${questions.length === 1 ? '' : 's'} open</span></div></article>
  <article class="block filled" id="demo-design" data-title="Design"><div class="head"><h3><a href="design.html">The design space →</a></h3></div><div class="body"><p>Tokens as swatches with the decision that chose them, contrast computed, the people, the parts, the patterns — every value copies in the form an editor wants.</p></div><div class="foot"><span class="src">boss design</span></div></article>
  <article class="block filled" id="demo-board" data-title="Board"><div class="head"><h3><a href="board.html">The board →</a></h3></div><div class="body"><p>Every idea and feature by where it stands — captured, taking shape, building, shipped, parked — read from the records' own status lines.</p></div><div class="foot"><span class="src">boss board --html</span></div></article>
  <article class="block filled" id="demo-folders" data-title="Folders"><div class="head"><h3><a href="folders.html">The folders →</a></h3></div><div class="body"><p>How the project is organised on disk, and which verb writes where — read from the tree after rendering.</p></div><div class="foot"><span class="src">the demo project's tree</span></div></article>
  <article class="block filled" id="demo-inside" data-title="Inside"><div class="head"><h3><a href="inside.html">Inside the folder →</a></h3></div><div class="body"><p>The CLAUDE.md, an agent, a skill and the conscience hook an install lays down — the shipped files, unedited.</p></div><div class="foot"><span class="src">stages/ · as shipped</span></div></article>
</div>
<p class="t-small" style="margin-top:24px">No faces: the founders are fictional, and BOSS never draws a stand-in for a person with no photo. No real company is a rival here. What you see is the render's honesty, not a brochure — the questions still open on the playbook are open on purpose only when a page says so.</p>`));
    return { out, questions, line: questionsLine(questions) };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  const r = generate({ check });
  if (check) { console.log(r.line); for (const q of r.questions) console.log(`  · ${q.title} — ${q.line}`); rmSync(r.dir, { recursive: true, force: true }); }
  else console.log(`  ✦ demo → ${relative(ROOT, r.out)}/ · ${r.line}`);
}
